### ISSUE TITLE
在伺服器頻道要求開啟全新的對話時遇到錯誤 （...reset）

### ISSUE THREAD

**Issue by LianSheng197** [suzumiyahifumi/Discord-ChatGPT-Bot-docker#1]
因為在反覆對談中遇到了 4096 token 的限制，我想說也許需要手動 reset，然後才發現這個問題。

在伺服器頻道的對話中輸入「...reset」時將觸發這個錯誤：

![image](https://user-images.githubusercontent.com/18535495/222712570-c037afdb-215d-49aa-a805-52716e3f9447.png)

**Comment by suzumiyahifumi** [comment]
會馬上修復錯誤，感謝通報

**Comment by suzumiyahifumi** [comment]
已經修復囉！
