### ISSUE TITLE
是否存在特殊的手法以規避 token limit？

### ISSUE THREAD

**Issue by LianSheng197** [suzumiyahifumi/Discord-ChatGPT-Bot-docker#2]
已知此專案在某個對話中延續太多後將會觸發 token limit，此時只能使用 reset 的方式重設對話。  

![image](https://user-images.githubusercontent.com/18535495/222905897-db95352d-3c2f-47e6-98e4-e3f571e9f607.png)

我對這個限制的理解是 OpenAI 從 API 源頭直接控管的，只要是使用官方 API 的話就只能這樣。  

![image](https://user-images.githubusercontent.com/18535495/222905989-7ab04e7f-6275-44f8-a82a-91a74b1401a6.png)

從 `keyv` 在 `MongoDB` 儲存的資料可以發現，目前此專案使用的 model 是 `text-davinci-003`  

![image](https://user-images.githubusercontent.com/18535495/222906139-0fff481f-fc14-46b3-84ff-eb11aa595e77.png)

所以要嘛是接受這個限制，要嘛就是用其他開源的逆向 API...

我在使用作者提供的另一個機器人 `@ChatGPT#3097` 時卻從未遇過這個狀況 (token limit)。  
不知道是不是有什麼特殊的做法能同時滿足對話的延續且避開限制？  
又或者其實那隻機器人背後並不是使用官方的 API？

**Comment by suzumiyahifumi** [comment]
以我目前使用情況也沒有遇過這種壯況，你可以嘗試檢查 https://github.com/transitive-bullshit/chatgpt-api#readme 這個 repo ，我的所有服務都是基於本 repo 至做的。
有問題再回報，我也會先檢查。

**Comment by LianSheng197** [comment]
好哦，我先研究看看。謝謝回應。

**Comment by LianSheng197** [comment]
看起來他們也有遇到這種狀況...

> There will always be context limits (4096 tokens)

https://github.com/transitive-bullshit/chatgpt-api/issues/272#issuecomment-1435949458


這就讓我很好奇了，為什麼我不曾在 `@ChatGPT#3097` 看到這個限制XD
